version: '2'

services: 
  express:
    build: .
    image: github.com/mprather1/docker_express
    container_name: shintech-express
    env_file:
      - ./docker.env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/data